dbt_streamazon:
  outputs:
    dev:
      dataset: streamazon_stg
      fixed_retries: 1
      location: us-east1
      method: oauth
      priority: interactive
      project: "streaming-amazon-sales"
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: streamazon_prod
      fixed_retries: 1
      location: us-east1
      method: oauth
      priority: interactive
      project: "streaming-amazon-sales"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev